version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk_network
    mem_reservation: 1g   # Mínimo 1GB de RAM
    mem_limit: 2g        # Máximo 2GB de RAM

  logstash:
    image: docker.elastic.co/logstash/logstash:7.14.0
    container_name: logstash
    volumes:
      - ./logstash/config/:/usr/share/logstash/pipeline/
    environment:
      - "ELASTICSEARCH_HOST=elasticsearch"
      - "ELASTICSEARCH_PORT=9200"
    ports:
      - "5000:5000"
      - "9600:9600"
    networks:
      - elk_network
    mem_reservation: 1g   # Mínimo 1GB de RAM
    mem_limit: 2g        # Máximo 2GB de RAM

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.0
    container_name: kibana
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
    ports:
      - "5601:5601"
    networks:
      - elk_network
    mem_reservation: 1g   # Mínimo 1GB de RAM
    mem_limit: 2g        # Máximo 2GB de RAM

networks:
  elk_network:
    driver: bridge
